### ISSUE TITLE
Investigate travis build issues

### ISSUE THREAD

**Issue by vmadman** [Dasix/grits#33]
### Initial warning message:

```
Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
```
### Errors/warnings during NPM install

```
make: Entering directory `/home/travis/build/Dasix/grits/node_modules/livereloadx/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from ../src/validation.cc:7:0:
/home/travis/.node-gyp/4.3.2/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.3.2/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.3.2/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
In file included from ../node_modules/nan/nan.h:194:0,
                 from ../src/validation.cc:15:
../node_modules/nan/nan_maybe_43_inl.h:13:1: error: expected unqualified-id before ‘using’

...

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.3.2/bin/node" "/home/travis/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/Dasix/grits/node_modules/livereloadx/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```
### Failures in watcher tests ..

**1:**

```
Error in wAddState( 'content-one' )
  -> fs.copyAsync
    -> from : /home/travis/build/Dasix/grits/test/fixtures/watcher/states/content-one/content/subdir
    -> to   : /home/travis/build/Dasix/grits/test/fixtures/watcher/src/content/subdir

[ { [Error: ENOENT: no such file or directory, unlink '/home/travis/build/Dasix/grits/test/fixtures/watcher/src/content/subdir/morecontent.md']
    errno: -2,
    code: 'ENOENT',
    syscall: 'unlink',
    path: '/home/travis/build/Dasix/grits/test/fixtures/watcher/src/content/subdir/morecontent.md' } ]
```

**2:**

```
Error in wAddState( 'content-one' )
  -> fs.copyAsync
    -> from : /home/travis/build/Dasix/grits/test/fixtures/watcher/states/content-one/content/subdir/morecontent.md
    -> to   : /home/travis/build/Dasix/grits/test/fixtures/watcher/src/content/subdir/morecontent.md

[ { [Error: ENOENT: no such file or directory, chmod '/home/travis/build/Dasix/grits/test/fixtures/watcher/src/content/subdir/morecontent.md']
    errno: -2,
    code: 'ENOENT',
    syscall: 'chmod',
    path: '/home/travis/build/Dasix/grits/test/fixtures/watcher/src/content/subdir/morecontent.md' } ]
```

**3:**

```
Error in wAddState( 'static-content-one' )
  -> fs.copyAsync
    -> from : /home/travis/build/Dasix/grits/test/fixtures/watcher/states/static-content-one/static/images
    -> to   : /home/travis/build/Dasix/grits/test/fixtures/watcher/src/static/images

[ { [Error: ENOENT: no such file or directory, unlink '/home/travis/build/Dasix/grits/test/fixtures/watcher/src/static/images/hello-world-b.png']
    errno: -2,
    code: 'ENOENT',
    syscall: 'unlink',
    path: '/home/travis/build/Dasix/grits/test/fixtures/watcher/src/static/images/hello-world-b.png' } ]
```

**Comment by vmadman** [comment]
Fixed most of those but the wAddState errors still exist.  No idea what's up, yet ..
